apiVersion: deployments.plural.sh/v1alpha1
kind: GeneratedSecret
metadata:
  name: plrl-elastic-user
  namespace: default
spec:
  destinations:
    - name: plrl-elastic-user
      namespace: elastic
    - name: plrl-elastic-user
      namespace: infra
    - name: plrl-elastic-user
      namespace: plrl-deploy-operator
  template:
    password: "{{ 32 | randAlphaNum }}"
    roles: admin
    user: plrl
